flowchart TB
  title[Escenario 4: Cuello de Botella / Red Lenta]
  
  Start(("Inicio")) --> Init["Handheld: Descargar BD local"]
  Init --> Scan["Handheld: Escaneo QR"]
  Scan --> IsValid{"¿Boleto Valido?"}
	Scan --> Log["Handheld: Guarda Bitacora en BD local"]
  IsValid -- NO --> Deny["⛔ ACCESO DENEGADO<br>Boleto Falso/No vendido"]
  IsValid -- SI --> IsUsed{"¿Ya Usado?"}
  IsUsed -- SI --> DenyDup["⛔ DENEGADO<br>Intento de Replay"]
  IsUsed -- NO --> CheckZone{"¿Zona Correcta?"}
  CheckZone -- NO --> WrongZone["⛔ ZONA ERRÓNEA<br>Redirigir a su puerta"]
  CheckZone -- SI --> Grant["✅ ACCESO PERMITIDO"]
	Grant --> End(("Fin"))
  Log --> DoSync{"¿Sincronizar con Bastion?"}
  DoSync -- SI --> Sync["Handheld: Sincronizar con Bastion"]
  DoSync -- NO --> WaitSync["Esperar 10 seg"]
  Sync --> Timeout{¿Tiempo de Respuesta Prolongado?}
  Timeout -- NO --> SyncOk[✅ SINCRONIZACION EXITOSA]
  Timeout -- SI --> SyncFail{¿Pasar a Modo Offline}
  SyncFail -- NO --> KeepOnline[Continuar en Modo Online]
  SyncFail -- SI --> ChangeOffline["⛔ MODO OFFILINE<br>Handheld se sincronizara una vez que regrese a modo online"]
  ChangeOffline --> ReturnOnline{¿Regresar a Modo Online?}
  ReturnOnline -- NO --> ChangeOffline
  ReturnOnline -- SI --> KeepOnline
  KeepOnline --> DoSync
  WaitSync --> DoSync

    Log:::action
    Init:::action
    Scan:::action
    IsValid:::logic
    Deny:::error
    IsUsed:::logic
    DenyDup:::error
    CheckZone:::logic
    WrongZone:::error
    Grant:::success
    DoSync:::logic
    Sync:::action
    Timeout:::logic
    SyncOk:::success
    SyncFail:::logic
    KeepOnline:::action
    ChangeOffline:::error
    ReturnOnline:::logic

  classDef success fill:#d4edda,stroke:#28a745,color:#155724,stroke-width:2px
  classDef error fill:#f8d7da,stroke:#dc3545,color:#721c24,stroke-width:2px
  classDef logic fill:#fff3cd,stroke:#ffc107,color:#856404,stroke-dasharray: 5 5
  classDef action fill:#e2e3e5,stroke:#6c757d,color:#383d41
