graph LR
    api[API de Payments]

    subgraph backing[Servicios de Respaldo]
        postgres[(PostgreSQL)]
        redis[(Redis)]
        rabbitmq>RabbitMQ]
    end

    payment_gateway[Pasarela de Pagos]

    api --> postgres
    api --> redis
    api --> rabbitmq
    api --> payment_gateway

    %% Node styles
    classDef apiStyle fill:#FF9F40,stroke:#FF9F40,color:#fff
    classDef storageStyle fill:#95a5a6,stroke:#95a5a6,color:#fff
    classDef externalStyle fill:#E8E8E8,stroke:#E8E8E8,color:#333

    class api apiStyle
    class postgres,redis,rabbitmq storageStyle
    class payment_gateway externalStyle

    %% Subgraph styling
    style backing fill:#e0e3e4,stroke:#e0e3e4
