%%{init: {"flowchart": {"defaultRenderer": "elk"}} }%%
graph LR
    source[Source Code]
    github[GitHub Actions]
    ecr[AWS ECR]
    ec2[EC2 / Docker]
    admin_api[Admin API]
    browser[Browser]

    source --> github
    github --> ecr
    ecr --> ec2
    browser -->|SignalR| ec2
    ec2 --> admin_api

    %% Node styles
    classDef devStyle fill:#7B68EE,stroke:#7B68EE,color:#fff
    classDef cicdStyle fill:#50C878,stroke:#50C878,color:#fff
    classDef hostingStyle fill:#FF9F40,stroke:#FF9F40,color:#fff
    classDef apiStyle fill:#50C878,stroke:#50C878,color:#fff
    classDef clientStyle fill:#f95d6a,stroke:#f95d6a,color:#fff

    class source devStyle
    class github cicdStyle
    class ecr,ec2 hostingStyle
    class admin_api apiStyle
    class browser clientStyle
